/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Channel,
  CommunityOverview,
  Giveaway,
  GiveawayInput,
  HealthStatus,
  Message,
  MessageInput
} from './api.schemas';

import { customFetch } from './custom-fetch';
import type { ErrorType , BodyType } from './custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getHealthCheckUrl = () => {




  return `/api/healthz`
}

/**
 * Returns server health status
 * @summary Health check
 */
export const healthCheck = async ( options?: Parameters<typeof customFetch>[1]): Promise<HealthStatus> => {

  return customFetch<HealthStatus>(getHealthCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthCheckQueryKey = () => {
    return [
    `/api/healthz`
    ] as const;
    }


export const getHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) => healthCheck({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>
export type HealthCheckQueryError = ErrorType<unknown>


/**
 * @summary Health check
 */

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetCommunityOverviewUrl = () => {




  return `/api/community/overview`
}

/**
 * @summary Get community overview
 */
export const getCommunityOverview = async ( options?: Parameters<typeof customFetch>[1]): Promise<CommunityOverview> => {

  return customFetch<CommunityOverview>(getGetCommunityOverviewUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCommunityOverviewQueryKey = () => {
    return [
    `/api/community/overview`
    ] as const;
    }


export const getGetCommunityOverviewQueryOptions = <TData = Awaited<ReturnType<typeof getCommunityOverview>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCommunityOverview>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCommunityOverviewQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCommunityOverview>>> = ({ signal }) => getCommunityOverview({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCommunityOverview>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCommunityOverviewQueryResult = NonNullable<Awaited<ReturnType<typeof getCommunityOverview>>>
export type GetCommunityOverviewQueryError = ErrorType<unknown>


/**
 * @summary Get community overview
 */

export function useGetCommunityOverview<TData = Awaited<ReturnType<typeof getCommunityOverview>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCommunityOverview>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetCommunityOverviewQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getListChannelsUrl = () => {




  return `/api/channels`
}

/**
 * @summary List synced channels
 */
export const listChannels = async ( options?: Parameters<typeof customFetch>[1]): Promise<Channel[]> => {

  return customFetch<Channel[]>(getListChannelsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListChannelsQueryKey = () => {
    return [
    `/api/channels`
    ] as const;
    }


export const getListChannelsQueryOptions = <TData = Awaited<ReturnType<typeof listChannels>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listChannels>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListChannelsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listChannels>>> = ({ signal }) => listChannels({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listChannels>>, TError, TData> & { queryKey: QueryKey }
}

export type ListChannelsQueryResult = NonNullable<Awaited<ReturnType<typeof listChannels>>>
export type ListChannelsQueryError = ErrorType<unknown>


/**
 * @summary List synced channels
 */

export function useListChannels<TData = Awaited<ReturnType<typeof listChannels>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listChannels>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListChannelsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getListMessagesUrl = (channelId: string,) => {




  return `/api/channels/${channelId}/messages`
}

/**
 * @summary List messages in a channel
 */
export const listMessages = async (channelId: string, options?: Parameters<typeof customFetch>[1]): Promise<Message[]> => {

  return customFetch<Message[]>(getListMessagesUrl(channelId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListMessagesQueryKey = (channelId: string,) => {
    return [
    `/api/channels/${channelId}/messages`
    ] as const;
    }


export const getListMessagesQueryOptions = <TData = Awaited<ReturnType<typeof listMessages>>, TError = ErrorType<unknown>>(channelId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listMessages>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMessagesQueryKey(channelId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMessages>>> = ({ signal }) => listMessages(channelId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: channelId !== null && channelId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMessages>>, TError, TData> & { queryKey: QueryKey }
}

export type ListMessagesQueryResult = NonNullable<Awaited<ReturnType<typeof listMessages>>>
export type ListMessagesQueryError = ErrorType<unknown>


/**
 * @summary List messages in a channel
 */

export function useListMessages<TData = Awaited<ReturnType<typeof listMessages>>, TError = ErrorType<unknown>>(
 channelId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listMessages>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListMessagesQueryOptions(channelId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getCreateMessageUrl = (channelId: string,) => {




  return `/api/channels/${channelId}/messages`
}

/**
 * @summary Send a message
 */
export const createMessage = async (channelId: string,
    messageInput: MessageInput, options?: Parameters<typeof customFetch>[1]): Promise<Message> => {

  return customFetch<Message>(getCreateMessageUrl(channelId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(messageInput)
  }
);}





export const getCreateMessageMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMessage>>, TError,{channelId: string;data: BodyType<MessageInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createMessage>>, TError,{channelId: string;data: BodyType<MessageInput>}, TContext> => {

const mutationKey = ['createMessage'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createMessage>>, {channelId: string;data: BodyType<MessageInput>}> = (props) => {
          const {channelId,data} = props ?? {};

          return  createMessage(channelId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateMessageMutationResult = NonNullable<Awaited<ReturnType<typeof createMessage>>>
    export type CreateMessageMutationBody = BodyType<MessageInput>
    export type CreateMessageMutationError = ErrorType<unknown>

    /**
 * @summary Send a message
 */
export const useCreateMessage = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMessage>>, TError,{channelId: string;data: BodyType<MessageInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createMessage>>,
        TError,
        {channelId: string;data: BodyType<MessageInput>},
        TContext
      > => {
      return useMutation(getCreateMessageMutationOptions(options));
    }

export const getListGiveawaysUrl = () => {




  return `/api/giveaways`
}

/**
 * @summary List active giveaways
 */
export const listGiveaways = async ( options?: Parameters<typeof customFetch>[1]): Promise<Giveaway[]> => {

  return customFetch<Giveaway[]>(getListGiveawaysUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListGiveawaysQueryKey = () => {
    return [
    `/api/giveaways`
    ] as const;
    }


export const getListGiveawaysQueryOptions = <TData = Awaited<ReturnType<typeof listGiveaways>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listGiveaways>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListGiveawaysQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listGiveaways>>> = ({ signal }) => listGiveaways({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listGiveaways>>, TError, TData> & { queryKey: QueryKey }
}

export type ListGiveawaysQueryResult = NonNullable<Awaited<ReturnType<typeof listGiveaways>>>
export type ListGiveawaysQueryError = ErrorType<unknown>


/**
 * @summary List active giveaways
 */

export function useListGiveaways<TData = Awaited<ReturnType<typeof listGiveaways>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listGiveaways>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListGiveawaysQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getCreateGiveawayUrl = () => {




  return `/api/giveaways`
}

/**
 * @summary Create a giveaway
 */
export const createGiveaway = async (giveawayInput: GiveawayInput, options?: Parameters<typeof customFetch>[1]): Promise<Giveaway> => {

  return customFetch<Giveaway>(getCreateGiveawayUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(giveawayInput)
  }
);}





export const getCreateGiveawayMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGiveaway>>, TError,{data: BodyType<GiveawayInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createGiveaway>>, TError,{data: BodyType<GiveawayInput>}, TContext> => {

const mutationKey = ['createGiveaway'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createGiveaway>>, {data: BodyType<GiveawayInput>}> = (props) => {
          const {data} = props ?? {};

          return  createGiveaway(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateGiveawayMutationResult = NonNullable<Awaited<ReturnType<typeof createGiveaway>>>
    export type CreateGiveawayMutationBody = BodyType<GiveawayInput>
    export type CreateGiveawayMutationError = ErrorType<unknown>

    /**
 * @summary Create a giveaway
 */
export const useCreateGiveaway = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGiveaway>>, TError,{data: BodyType<GiveawayInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createGiveaway>>,
        TError,
        {data: BodyType<GiveawayInput>},
        TContext
      > => {
      return useMutation(getCreateGiveawayMutationOptions(options));
    }

export const getJoinGiveawayUrl = (giveawayId: string,) => {




  return `/api/giveaways/${giveawayId}/join`
}

/**
 * @summary Join a giveaway
 */
export const joinGiveaway = async (giveawayId: string, options?: Parameters<typeof customFetch>[1]): Promise<Giveaway> => {

  return customFetch<Giveaway>(getJoinGiveawayUrl(giveawayId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getJoinGiveawayMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof joinGiveaway>>, TError,{giveawayId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof joinGiveaway>>, TError,{giveawayId: string}, TContext> => {

const mutationKey = ['joinGiveaway'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof joinGiveaway>>, {giveawayId: string}> = (props) => {
          const {giveawayId} = props ?? {};

          return  joinGiveaway(giveawayId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type JoinGiveawayMutationResult = NonNullable<Awaited<ReturnType<typeof joinGiveaway>>>

    export type JoinGiveawayMutationError = ErrorType<unknown>

    /**
 * @summary Join a giveaway
 */
export const useJoinGiveaway = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof joinGiveaway>>, TError,{giveawayId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof joinGiveaway>>,
        TError,
        {giveawayId: string},
        TContext
      > => {
      return useMutation(getJoinGiveawayMutationOptions(options));
    }

