/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export type UserStatus = typeof UserStatus[keyof typeof UserStatus];


export const UserStatus = {
  online: 'online',
  idle: 'idle',
  offline: 'offline',
} as const;

export interface User {
  id: string;
  name: string;
  handle: string;
  avatarUrl: string;
  status: UserStatus;
  /** @nullable */
  role?: string | null;
  /** @nullable */
  badge?: string | null;
}

export type ChannelKind = typeof ChannelKind[keyof typeof ChannelKind];


export const ChannelKind = {
  text: 'text',
  announcement: 'announcement',
  voice: 'voice',
} as const;

export interface Channel {
  id: string;
  name: string;
  kind: ChannelKind;
  unread: number;
  /** @nullable */
  category?: string | null;
}

export type MessageSource = typeof MessageSource[keyof typeof MessageSource];


export const MessageSource = {
  website: 'website',
  discord: 'discord',
} as const;

export interface Message {
  id: string;
  channelId: string;
  author: User;
  content: string;
  createdAt: string;
  source: MessageSource;
  mentions?: string[];
}

export interface MessageInput {
  /** @minLength 1 */
  content: string;
  mentions?: string[];
}

export type GiveawayStatus = typeof GiveawayStatus[keyof typeof GiveawayStatus];


export const GiveawayStatus = {
  active: 'active',
  ended: 'ended',
  cancelled: 'cancelled',
} as const;

export interface Giveaway {
  id: string;
  title: string;
  prize: string;
  description: string;
  /** @nullable */
  previewUrl?: string | null;
  endsAt: string;
  participants: number;
  status: GiveawayStatus;
  /** @nullable */
  winner?: string | null;
}

export interface GiveawayInput {
  /** @minLength 1 */
  title: string;
  /** @minLength 1 */
  prize: string;
  description: string;
  /** @nullable */
  previewUrl?: string | null;
  endsAt: string;
}

export interface CommunityOverview {
  serverName: string;
  logoUrl: string;
  developer: User;
  onlineCount: number;
  activeChannels: number;
  weeklyRank: number;
  featuredGame: string;
  /** @nullable */
  announcement?: string | null;
}

